version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile_dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    container_name: frontend_dev
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    container_name: backend_dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
