version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./backend/database/scripts:/docker-entrypoint-initdb.d
      - ./backend/database/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile_dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    container_name: frontend_dev
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    container_name: backend_dev
    networks:
      - app-network
    depends_on:
      - db
  
volumes:
  db-store:
  node_modules:

networks:
  app-network:
    driver: bridge
