version: '3'

services:
  db:
    build: 
      context: ./backend
      dockerfile: Dockerfile_postgres
    image: sudoku-app-db
    container_name: sudoku-app-db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile_dev
    ports:
      - "8000:8000"
    image: sudoku-app-backend
    container_name: sudoku-app-backend
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
