version: '3'

services:
  db:
    build: 
      context: ./backend
      dockerfile: Dockerfile_postgres
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile_dev
    ports:
      - "8000:8000"
    container_name: backend_dev
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
