# 開発用のDockerfile
# ビルドステージ
FROM python:3.11 as builder

# 作業ディレクトリの設定
WORKDIR /app

# 必要なパッケージをインストール
RUN apt-get update && \
    apt-get install -y \
    curl

# 依存関係をインストール
COPY requirements.txt ./
RUN pip install -r requirements.txt

# ホスト側のファイルをコンテナへコピー
COPY assets/ ./assets/
COPY conf/ ./conf/
COPY core/ ./core/
COPY database/ ./database/
COPY env/ ./env/
COPY logger/ ./logger/
COPY util/ ./util/
COPY server.py ./

# ランタイムステージ
FROM python:3.11-slim as production
RUN apt-get update && \
    apt-get install -y \
    curl

COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /app/ ./

# 開発サーバー用のポートを解放
EXPOSE 8000

# 開発サーバーを起動
CMD ["python", "-u", "server.py"]