import os
from env.app_env import app_env

LOCAL_POSTGRES_HOST = app_env['POSTGRES_HOST']
LOCAL_POSTGRES_DB = app_env['POSTGRES_DB']
LOCAL_POSTGRES_USER = app_env['POSTGRES_USER']
LOCAL_POSTGRES_PASSWORD = app_env['POSTGRES_PASSWORD']

# DBの設定値を読み込み
# 開発環境の設定値はAWS Secret Manager参照
POSTGRES_HOST = os.getenv('POSTGRES_HOST', LOCAL_POSTGRES_HOST)
POSTGRES_DB =  os.getenv('POSTGRES_DB', LOCAL_POSTGRES_DB)
POSTGRES_USER = os.getenv('POSTGRES_USER', LOCAL_POSTGRES_USER)
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD', LOCAL_POSTGRES_PASSWORD)

# フロントエンドURLを読み込み
FRONTEND_URL = app_env['FRONTEND_URL']